import os
import datetime
# import os
print("Current Working Directory:", os.getcwd())
def save_document(response_text: str, directory: str = "output"):
    """Export travel plan to Markdown file with proper formatting"""

    print("✅ save_document() function called")

    if not response_text:
        print("❌ No response text provided.")
        return None

    try:
        # Create folder if it doesn't exist
        os.makedirs(directory, exist_ok=True)

        # Generate timestamp
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"AI_Trip_Planner_{timestamp}.md"
        filepath = os.path.join(directory, filename)

        # Create markdown content (clean formatting, no extra indentation)
        markdown_content = f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""

        # Write file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(markdown_content)

        print("✅ Markdown file successfully saved!")
        print("📂 Full Path:", os.path.abspath(filepath))

        return filepath

    except Exception as e:
        print("❌ Error saving markdown file:", e)
        return None
    

if __name__ == "__main__":
    # print("🔥 File is running")
    save_document("This is a test travel plan.")